In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

In [2]:
import tensorflow as tf
tfe = tf.contrib.eager

tf.enable_eager_execution()

In [3]:
layer = tf.keras.layers.Dense(100)

layer = tf.keras.layers.Dense(10, input_shape=(None, 5))


In [4]:
layer(tf.zeros([10,5]))

<tf.Tensor: id=30, shape=(10, 10), dtype=float32, numpy=
array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)>

In [5]:
layer.variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.02592701, -0.04494846,  0.38978559, -0.19861373, -0.01626396,
          0.32118917, -0.25319791,  0.26652598,  0.03003538, -0.31795564],
        [ 0.14495075,  0.60798973, -0.24046963,  0.06103992, -0.18655753,
         -0.5703063 ,  0.53602856, -0.21810687, -0.33020231,  0.39588243],
        [-0.53173423, -0.61521971, -0.38816369, -0.18135893, -0.31740785,
         -0.38138631, -0.38426292,  0.62440139, -0.17155582, -0.19519821],
        [-0.63076109, -0.05454659,  0.15319109, -0.1867789 ,  0.02973729,
         -0.52510333,  0.23782462, -0.33098987, -0.5367738 , -0.14855912],
        [-0.24317858,  0.32489753, -0.19881684, -0.25986052, -0.26436037,
          0.3517487 ,  0.06566656,  0.50376362,  0.58992916, -0.15228468]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.], dtype=float32)>]

In [6]:
layer.kernel, layer.bias

(<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.02592701, -0.04494846,  0.38978559, -0.19861373, -0.01626396,
          0.32118917, -0.25319791,  0.26652598,  0.03003538, -0.31795564],
        [ 0.14495075,  0.60798973, -0.24046963,  0.06103992, -0.18655753,
         -0.5703063 ,  0.53602856, -0.21810687, -0.33020231,  0.39588243],
        [-0.53173423, -0.61521971, -0.38816369, -0.18135893, -0.31740785,
         -0.38138631, -0.38426292,  0.62440139, -0.17155582, -0.19519821],
        [-0.63076109, -0.05454659,  0.15319109, -0.1867789 ,  0.02973729,
         -0.52510333,  0.23782462, -0.33098987, -0.5367738 , -0.14855912],
        [-0.24317858,  0.32489753, -0.19881684, -0.25986052, -0.26436037,
          0.3517487 ,  0.06566656,  0.50376362,  0.58992916, -0.15228468]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.], dtype=float32)>)

In [9]:
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs
        
    def bulid(self, input_shape):
        self.kernel = self.add_variable("kernel", shape=[input_shape[-1].value, self.num_outputs])
    
    def call(self, input):
        return tf.matmul(input, self.kernel)

layer = MyDenseLayer(10)
print(layer(tf.zeros([10,5])))
print(layer.variables)

AttributeError: 'MyDenseLayer' object has no attribute 'kernel'

In [10]:
my_seq = tf.keras.Sequential([tf.keras.layers.Conv2D(1, (1, 1)),
                               tf.keras.layers.BatchNormalization(),
                               tf.keras.layers.Conv2D(2, 1, 
                                                      padding='same'),
                               tf.keras.layers.BatchNormalization(),
                               tf.keras.layers.Conv2D(3, (1, 1)),
                               tf.keras.layers.BatchNormalization()])
my_seq(tf.zeros([1, 2, 3, 3]))

<tf.Tensor: id=267, shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]]], dtype=float32)>