In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

In [1]:
"""
Eager execution makes TensorFlow evaluate operations immediately, returning concrete values instead of creating a computational graph that is executed later.
If you are used to a REPL or the python interactive console, this feels familiar.
Eager execution is available in Tensorlow >=1.8.
"""

import tensorflow as tf

tf.enable_eager_execution()

In [3]:
print(tf.add(1,2))
print(tf.add([1, 2], [3,4]))
print(tf.square(5))
print(tf.reduce_sum([1,2,3]))
print(tf.encode_base64("hello world"))

print(tf.square(2) + tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(b'aGVsbG8gd29ybGQ', shape=(), dtype=string)
tf.Tensor(13, shape=(), dtype=int32)


In [4]:
x = tf.matmul([[1]], [[2,3]])
print(x.shape)
print(x.dtype)

(1, 2)
<dtype: 'int32'>


In [5]:
import numpy as np

ndarray = np.ones([3,3])
print(ndarray)

print("Tensorflow operations convert numpy arrays to Tensors automatically")
tensor = tf.multiply(ndarray, 42)
print(tensor)

print("And Numpy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor, 1))

print("The .numpy() method explicitly convert Tensors to numpy array")
print(tensor.numpy())


[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
Tensorflow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[ 42.  42.  42.]
 [ 42.  42.  42.]
 [ 42.  42.  42.]], shape=(3, 3), dtype=float64)
And Numpy operations convert Tensors to numpy arrays automatically
[[ 43.  43.  43.]
 [ 43.  43.  43.]
 [ 43.  43.  43.]]
The .numpy() method explicitly convert Tensors to numpy array
[[ 42.  42.  42.]
 [ 42.  42.  42.]
 [ 42.  42.  42.]]


In [6]:
x = tf.random_uniform([3,3])
print(x)

print("Is there a GPU available: "),
print(tf.test.is_gpu_available())

print("Is the Tensor on GPU #0: "),
print(x.device.endswith('GPU:0'))

tf.Tensor(
[[ 0.26829946  0.4304719   0.68782997]
 [ 0.96197784  0.89611411  0.97130191]
 [ 0.59214783  0.54587913  0.18757272]], shape=(3, 3), dtype=float32)
Is there a GPU available: 
False
Is the Tensor on GPU #0: 
False


In [7]:
def time_matmul(x):
  %timeit tf.matmul(x, x)

# Force execution on CPU
print("On CPU:")
with tf.device("CPU:0"):
  x = tf.random_uniform([1000, 1000])
  assert x.device.endswith("CPU:0")
  time_matmul(x)

# Force execution on GPU #0 if available
if tf.test.is_gpu_available():
  with tf.device("GPU:0"): # Or GPU:1 for the 2nd GPU, GPU:2 for the 3rd etc.
    x = tf.random_uniform([1000, 1000])
    assert x.device.endswith("GPU:0")
    time_matmul(x)

On CPU:
34.6 ms ± 3.24 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6])

import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
    f.write("""Line 1
Line 2
Line 3
    """)
    
ds_file = tf.data.TextLineDataset(filename)


In [9]:
print(ds_tensors)
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)
ds_file = ds_file.batch(2)

<TensorSliceDataset shapes: (), types: tf.int32>


In [11]:
print('Elements of ds_tensors:')
for x in ds_tensors:
  print(x)

print('\nElements in ds_file:')
for x in ds_file:
  print(x)

Elements of ds_tensors:
tf.Tensor([4 9], shape=(2,), dtype=int32)
tf.Tensor([ 1 25], shape=(2,), dtype=int32)
tf.Tensor([36 16], shape=(2,), dtype=int32)

Elements in ds_file:
tf.Tensor([b'Line 1' b'Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'Line 3' b'    '], shape=(2,), dtype=string)


tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
